##------------------------------------------------------------------
##------SERVER CONFIGURATION----------------------------------------
##------------------------------------------------------------------
server:
  port: 8081
spring:
  application:
    name: gateway-api
  security:
    user:
      name: admin
      password: 12341234


##------------------------------------------------------------------
##------GATEWAY API CONFIGURATION-----------------------------------
##------------------------------------------------------------------
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:12341234@localhost:8081/eureka